// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32              `json:"id"`
	OrderNumber string             `json:"order_number"`
	CustomerID  pgtype.Text        `json:"customer_id"`
	CreatedBy   pgtype.Text        `json:"created_by"`
	TotalAmount pgtype.Int8        `json:"total_amount"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID          int32              `json:"id"`
	OrderID     pgtype.Int4        `json:"order_id"`
	ProductID   pgtype.Int4        `json:"product_id"`
	ProductCode pgtype.Text        `json:"product_code"`
	ProductName pgtype.Text        `json:"product_name"`
	UnitPrice   pgtype.Int8        `json:"unit_price"`
	Quantity    pgtype.Int4        `json:"quantity"`
	LineTotal   pgtype.Int8        `json:"line_total"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID           int32              `json:"id"`
	ProductID    string             `json:"product_id"`
	ProductName  string             `json:"product_name"`
	SupplierName string             `json:"supplier_name"`
	Category     string             `json:"category"`
	PriceIdr     int64              `json:"price_idr"`
	Stock        int32              `json:"stock"`
	CreatedBy    pgtype.Text        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	FullName     string           `json:"full_name"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
