// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID         int32            `json:"id"`
	CustomerID int32            `json:"customer_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type OrderItem struct {
	ID        int32 `json:"id"`
	OrderID   int32 `json:"order_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

type Product struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	PriceInIdr    int32            `json:"price_in_idr"`
	Quantity      int32            `json:"quantity"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	LowStockAlert pgtype.Bool      `json:"low_stock_alert"`
}
