// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID            int32              `json:"id"`
	OrderNumber   string             `json:"order_number"`
	CustomerName  string             `json:"customer_name"`
	TotalAmount   pgtype.Int4        `json:"total_amount"`
	Status        string             `json:"status"`
	Platform      string             `json:"platform"`
	Destination   string             `json:"destination"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IDFromProduct pgtype.Int4        `json:"id_from_product"`
	ProductID     pgtype.Text        `json:"product_id"`
	PriceIdr      pgtype.Int4        `json:"price_idr"`
}

type Product struct {
	ID           int32              `json:"id"`
	ProductID    string             `json:"product_id"`
	ProductName  string             `json:"product_name"`
	SupplierName string             `json:"supplier_name"`
	Category     string             `json:"category"`
	PriceIdr     int64              `json:"price_idr"`
	Stock        int32              `json:"stock"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	FullName     string           `json:"full_name"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Permissions  []string         `json:"permissions"`
}
