// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	// Orders
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (int32, error)
	// Products
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// internal/adapters/postgresql/sqlc/queries.sql
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetProductByProductID(ctx context.Context, productID string) (Product, error)
	GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (GetUserByUsernameOrEmailRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// Utility queries
	// This is a helper to get a next sequence number for product id generation if you prefer DB-side sequence.
	NextProductSequence(ctx context.Context) (int64, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UserByID(ctx context.Context, id int32) (UserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
