// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    order_number,
    product_id,
    customer_name,
    total_amount,
    status,
    platform,
    destination,
    price_idr,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, order_number, product_id, customer_name, total_amount, status, platform, destination, price_idr, created_at
`

type CreateOrderParams struct {
	OrderNumber  string             `json:"order_number"`
	ProductID    pgtype.Int4        `json:"product_id"`
	CustomerName string             `json:"customer_name"`
	TotalAmount  pgtype.Int4        `json:"total_amount"`
	Status       string             `json:"status"`
	Platform     string             `json:"platform"`
	Destination  string             `json:"destination"`
	PriceIdr     pgtype.Int4        `json:"price_idr"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CreateOrderRow struct {
	ID           int32              `json:"id"`
	OrderNumber  string             `json:"order_number"`
	ProductID    pgtype.Int4        `json:"product_id"`
	CustomerName string             `json:"customer_name"`
	TotalAmount  pgtype.Int4        `json:"total_amount"`
	Status       string             `json:"status"`
	Platform     string             `json:"platform"`
	Destination  string             `json:"destination"`
	PriceIdr     pgtype.Int4        `json:"price_idr"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Orders
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.ProductID,
		arg.CustomerName,
		arg.TotalAmount,
		arg.Status,
		arg.Platform,
		arg.Destination,
		arg.PriceIdr,
		arg.CreatedAt,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ProductID,
		&i.CustomerName,
		&i.TotalAmount,
		&i.Status,
		&i.Platform,
		&i.Destination,
		&i.PriceIdr,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (product_id, product_name, supplier_name, category, price_idr, stock)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, product_name, supplier_name, category, price_idr, stock, created_at
`

type CreateProductParams struct {
	ProductID    string `json:"product_id"`
	ProductName  string `json:"product_name"`
	SupplierName string `json:"supplier_name"`
	Category     string `json:"category"`
	PriceIdr     int64  `json:"price_idr"`
	Stock        int32  `json:"stock"`
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductID,
		arg.ProductName,
		arg.SupplierName,
		arg.Category,
		arg.PriceIdr,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (user_id, username, email, full_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, username, email, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	UserID       string `json:"user_id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateUserRow struct {
	ID        int32            `json:"id"`
	UserID    string           `json:"user_id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	FullName  string           `json:"full_name"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// internal/adapters/postgresql/sqlc/queries.sql
// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByProductID = `-- name: GetProductByProductID :one
SELECT
  id,
  product_id,
  product_name,
  supplier_name,
  category,
  price_idr,
  stock,
  created_at
FROM products
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetProductByProductID(ctx context.Context, productID string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByProductID, productID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, user_id, username, email, full_name, password_hash, role, created_at, updated_at
FROM users
WHERE username = $1 OR email = $2
LIMIT 1
`

type GetUserByUsernameOrEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type GetUserByUsernameOrEmailRow struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	FullName     string           `json:"full_name"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (GetUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
  order_number,
  product_id,
  customer_name,
  total_amount,
  status,
  platform,
  destination,
  price_idr,
  created_at
FROM orders
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrdersRow struct {
	OrderNumber  string             `json:"order_number"`
	ProductID    pgtype.Int4        `json:"product_id"`
	CustomerName string             `json:"customer_name"`
	TotalAmount  pgtype.Int4        `json:"total_amount"`
	Status       string             `json:"status"`
	Platform     string             `json:"platform"`
	Destination  string             `json:"destination"`
	PriceIdr     pgtype.Int4        `json:"price_idr"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.ProductID,
			&i.CustomerName,
			&i.TotalAmount,
			&i.Status,
			&i.Platform,
			&i.Destination,
			&i.PriceIdr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
  id,
  product_id,
  product_name,
  supplier_name,
  category,
  price_idr,
  stock,
  created_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.SupplierName,
			&i.Category,
			&i.PriceIdr,
			&i.Stock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, full_name, role, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	UserID    string           `json:"user_id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	FullName  string           `json:"full_name"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextProductSequence = `-- name: NextProductSequence :one

SELECT nextval('products_id_seq') as seq
`

// Utility queries
// This is a helper to get a next sequence number for product id generation if you prefer DB-side sequence.
func (q *Queries) NextProductSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextProductSequence)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, order_number, product_id, customer_name, total_amount, status, platform, destination, price_idr, created_at
`

type UpdateOrderStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

type UpdateOrderStatusRow struct {
	ID           int32              `json:"id"`
	OrderNumber  string             `json:"order_number"`
	ProductID    pgtype.Int4        `json:"product_id"`
	CustomerName string             `json:"customer_name"`
	TotalAmount  pgtype.Int4        `json:"total_amount"`
	Status       string             `json:"status"`
	Platform     string             `json:"platform"`
	Destination  string             `json:"destination"`
	PriceIdr     pgtype.Int4        `json:"price_idr"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i UpdateOrderStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.ProductID,
		&i.CustomerName,
		&i.TotalAmount,
		&i.Status,
		&i.Platform,
		&i.Destination,
		&i.PriceIdr,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE(NULLIF($2, ''), username),
    email = COALESCE(NULLIF($3, ''), email),
    full_name = COALESCE(NULLIF($4, ''), full_name),
    password_hash = COALESCE(NULLIF($5, ''), password_hash),
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, username, email, password_hash
`

type UpdateUserParams struct {
	ID      int32       `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

type UpdateUserRow struct {
	ID           int32  `json:"id"`
	FullName     string `json:"full_name"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, user_id, username, email, full_name, password_hash, role, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type UserByIDRow struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	FullName     string           `json:"full_name"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UserByID(ctx context.Context, id int32) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
