// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
    order_number,
    id_from_product,
    product_id,
    customer_name,
    platform,
    destination,
    total_amount,
    status,
    price_idr,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, order_number, customer_name, total_amount, status, platform, destination, created_at, updated_at, id_from_product, product_id, price_idr
`

type CreateOrderParams struct {
	OrderNumber   string             `json:"order_number"`
	IDFromProduct pgtype.Int4        `json:"id_from_product"`
	ProductID     pgtype.Text        `json:"product_id"`
	CustomerName  string             `json:"customer_name"`
	Platform      string             `json:"platform"`
	Destination   string             `json:"destination"`
	TotalAmount   pgtype.Int4        `json:"total_amount"`
	Status        string             `json:"status"`
	PriceIdr      pgtype.Int4        `json:"price_idr"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Orders
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.IDFromProduct,
		arg.ProductID,
		arg.CustomerName,
		arg.Platform,
		arg.Destination,
		arg.TotalAmount,
		arg.Status,
		arg.PriceIdr,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.TotalAmount,
		&i.Status,
		&i.Platform,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IDFromProduct,
		&i.ProductID,
		&i.PriceIdr,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (product_id, product_name, supplier_name, category, price_idr, stock)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, product_name, supplier_name, category, price_idr, stock, created_at, updated_at
`

type CreateProductParams struct {
	ProductID    string `json:"product_id"`
	ProductName  string `json:"product_name"`
	SupplierName string `json:"supplier_name"`
	Category     string `json:"category"`
	PriceIdr     int64  `json:"price_idr"`
	Stock        int32  `json:"stock"`
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductID,
		arg.ProductName,
		arg.SupplierName,
		arg.Category,
		arg.PriceIdr,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (user_id, username, email, full_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, username, email, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	UserID       string `json:"user_id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateUserRow struct {
	ID        int32            `json:"id"`
	UserID    string           `json:"user_id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	FullName  string           `json:"full_name"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// internal/adapters/postgresql/sqlc/queries.sql
// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getLastOrderNumber = `-- name: GetLastOrderNumber :one
SELECT order_number
FROM orders
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLastOrderNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLastOrderNumber)
	var order_number string
	err := row.Scan(&order_number)
	return order_number, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, customer_name, total_amount, status, platform, destination, created_at, updated_at, id_from_product, product_id, price_idr FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.TotalAmount,
		&i.Status,
		&i.Platform,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IDFromProduct,
		&i.ProductID,
		&i.PriceIdr,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  id,
  product_id,
  product_name,
  supplier_name,
  category,
  price_idr,
  stock,
  created_at,
  updated_at
FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, user_id, username, email, full_name, password_hash, role, created_at, updated_at
FROM users
WHERE username = $1 OR email = $2
LIMIT 1
`

type GetUserByUsernameOrEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type GetUserByUsernameOrEmailRow struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	FullName     string           `json:"full_name"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (GetUserByUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersWithProduct = `-- name: ListOrdersWithProduct :many
SELECT
  o.id,
  o.order_number,
  o.id_from_product,       -- FK ke products.id
  o.product_id,            -- kode produk (text)
  o.customer_name,
  o.total_amount,
  o.status,
  o.platform,
  o.destination,
  o.price_idr,             -- harga produk
  o.created_at,
  p.product_name
FROM orders o
JOIN products p ON o.id_from_product = p.id
ORDER BY o.id DESC
LIMIT $1 OFFSET $2
`

type ListOrdersWithProductParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrdersWithProductRow struct {
	ID            int32              `json:"id"`
	OrderNumber   string             `json:"order_number"`
	IDFromProduct pgtype.Int4        `json:"id_from_product"`
	ProductID     pgtype.Text        `json:"product_id"`
	CustomerName  string             `json:"customer_name"`
	TotalAmount   pgtype.Int4        `json:"total_amount"`
	Status        string             `json:"status"`
	Platform      string             `json:"platform"`
	Destination   string             `json:"destination"`
	PriceIdr      pgtype.Int4        `json:"price_idr"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProductName   string             `json:"product_name"`
}

func (q *Queries) ListOrdersWithProduct(ctx context.Context, arg ListOrdersWithProductParams) ([]ListOrdersWithProductRow, error) {
	rows, err := q.db.Query(ctx, listOrdersWithProduct, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersWithProductRow
	for rows.Next() {
		var i ListOrdersWithProductRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.IDFromProduct,
			&i.ProductID,
			&i.CustomerName,
			&i.TotalAmount,
			&i.Status,
			&i.Platform,
			&i.Destination,
			&i.PriceIdr,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
  id,
  product_id,
  product_name,
  supplier_name,
  category,
  price_idr,
  stock,
  created_at,
  updated_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.SupplierName,
			&i.Category,
			&i.PriceIdr,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
  id,
  user_id,
  username, 
  email, 
  full_name, 
  role, 
  permissions,
  created_at, 
  updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID          int32            `json:"id"`
	UserID      string           `json:"user_id"`
	Username    string           `json:"username"`
	Email       string           `json:"email"`
	FullName    string           `json:"full_name"`
	Role        string           `json:"role"`
	Permissions []string         `json:"permissions"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextProductSequence = `-- name: NextProductSequence :one

SELECT nextval('products_id_seq') as seq
`

// Utility queries
// This is a helper to get a next sequence number for product id generation if you prefer DB-side sequence.
func (q *Queries) NextProductSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextProductSequence)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, order_number, customer_name, total_amount, status, platform, destination, created_at, updated_at, id_from_product, product_id, price_idr
`

type UpdateOrderStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.TotalAmount,
		&i.Status,
		&i.Platform,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IDFromProduct,
		&i.ProductID,
		&i.PriceIdr,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET product_id    = $2,
    product_name  = $3,
    supplier_name = $4,
    category      = $5,
    price_idr     = $6,
    stock         = $7,
    updated_at    = now()
WHERE id = $1
RETURNING id, product_id, product_name, supplier_name, category, price_idr, stock, created_at, updated_at
`

type UpdateProductParams struct {
	ID           int32  `json:"id"`
	ProductID    string `json:"product_id"`
	ProductName  string `json:"product_name"`
	SupplierName string `json:"supplier_name"`
	Category     string `json:"category"`
	PriceIdr     int64  `json:"price_idr"`
	Stock        int32  `json:"stock"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.ProductID,
		arg.ProductName,
		arg.SupplierName,
		arg.Category,
		arg.PriceIdr,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, product_name, supplier_name, category, price_idr, stock, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID    int32 `json:"id"`
	Stock int32 `json:"stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStockByDelta = `-- name: UpdateProductStockByDelta :one
UPDATE products
SET stock = stock + $2,
    updated_at = now()
WHERE id = $1
  AND (stock + $2) >= 0
RETURNING id, product_id, product_name, supplier_name, category, price_idr, stock, created_at, updated_at
`

type UpdateProductStockByDeltaParams struct {
	ID    int32 `json:"id"`
	Stock int32 `json:"stock"`
}

func (q *Queries) UpdateProductStockByDelta(ctx context.Context, arg UpdateProductStockByDeltaParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStockByDelta, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.SupplierName,
		&i.Category,
		&i.PriceIdr,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE(NULLIF($2, ''), username),
    email = COALESCE(NULLIF($3, ''), email),
    full_name = COALESCE(NULLIF($4, ''), full_name),
    password_hash = COALESCE(NULLIF($5, ''), password_hash),
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, username, email, password_hash
`

type UpdateUserParams struct {
	ID      int32       `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

type UpdateUserRow struct {
	ID           int32  `json:"id"`
	FullName     string `json:"full_name"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :exec
UPDATE users
SET permissions = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPermissionsParams struct {
	ID          int32    `json:"id"`
	Permissions []string `json:"permissions"`
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateUserPermissions, arg.ID, arg.Permissions)
	return err
}

const userByID = `-- name: UserByID :one
SELECT id, user_id, username, email, full_name, password_hash, role, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type UserByIDRow struct {
	ID           int32            `json:"id"`
	UserID       string           `json:"user_id"`
	Username     string           `json:"username"`
	Email        string           `json:"email"`
	FullName     string           `json:"full_name"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UserByID(ctx context.Context, id int32) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
